---
title: "exploit capri output for land use and ecosystem services modelling"
author: "Sarah, Paul, Erik Oudejans (Object Vision BV)"
date: "December 15, 2021"
output:
  word_document: 
    toc: yes
  html_document: 
      toc: yes
---

```{r setup, include=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..") # file path relative to the root of the project directory
library(ggplot2)
library(rlang)
library(purrr)
library(dplyr)
library(hms)
library(tidyverse)
library(readxl)
library(zoo)
library(data.table)
library(vctrs)
library(gdxrrw)

```

## Parameters
```{r}
fldr_GAMS  <- "C:\\GAMS\\37"
datapath <- "C:\\Users\\Cicada\\Documents\\GeoDMS\\luisabees_r\\data"           # input
fldr_nominmax <- "C:\\Users\\Cicada\\Documents\\GeoDMS\\luisabees_r\\nominmax"  # output

```

## Initialize GAMS - eval=false
```{r}
igdx(fldr_GAMS)
```

# Read gdx files directly using rgdx.param from the gdxrrw package
## Read one file
```{r}

gdxfiles <- list.files(datapath, ".gdx", full.names = TRUE)
gdxfiles[1]
```
## Create a function that reads many files
```{r}

#' @param gdxfile character name of a gdx file
#' @return data frame 
readcaprioutput <- function(gdxfile, symName = "dataout",
                            names = c("RALL","EMPTY","COLS","ROWS","Y","VALUE")){
    message("\nReading ", gdxfile)
    capriout <- rgdx.param(gdxfile, symName = symName, names = names) 
    # Change factor to character variables
    capriout$RALL <- as.character(capriout$RALL)
    capriout$EMPTY <- as.character(capriout$EMPTY)
    capriout$COLS <- as.character(capriout$COLS)
    capriout$ROWS <- as.character(capriout$ROWS)
    # Change year from factor to a numeric variable
    capriout$Y <- as.numeric(as.character(capriout$Y))
    return(capriout)
}

#uniqueLanduseTypes <- unique(capriout[c("COLS")]);

# Use the function to read one file (takes 6 seconds)
#system.time(res_2_0810mtr_rd_ref <- readcaprioutput(gdxfiles[1]))

# Use the function to read 13 files (should take more than a minute)
caprilist <- lapply(gdxfiles, readcaprioutput)
capriout <- Reduce(rbind, caprilist)


# save the output to an R file
saveRDS(capriout, file.path(datapath, "capriout.rds"))

if(FALSE){ # Read the file
    readRDS(file.path(datapath, "capriout.rds"))
}
```

# Parse capriout data
## Create demand files for land use classes
```{r}
#unwanted labels EU27yr19

arable<-capriout %>% 
  select(-EMPTY) %>% 
  filter(COLS == "ARAB") %>%
  filter(ROWS == "LEVL") %>%
  filter(nchar(RALL)==8) %>%
  filter(RALL!='EU27yr19') %>%
  dplyr::arrange(RALL, Y)
perm<-capriout %>% 
  select(-EMPTY) %>% 
  filter(COLS == "PERM") %>% 
  filter(ROWS == "LEVL") %>% 
  filter(nchar(RALL)==8) %>%
  dplyr::arrange(RALL, Y)
necr<-capriout %>%            # new economic crops
  select(-EMPTY) %>% 
  filter(COLS == "NECR") %>% 
  filter(ROWS == "LEVL") %>% 
  filter(nchar(RALL)==8) %>%
  dplyr::arrange(RALL, Y)
grass<-capriout %>% 
  select(-EMPTY) %>% 
  filter(grepl("GRAI|GRAE" ,COLS)) %>%
  filter(ROWS == "LEVL") %>% 
  filter(nchar(RALL)==8) %>%
  dplyr::arrange(RALL, Y) %>%
  group_by(RALL,ROWS,Y) %>%
  summarise(amount_1000ha = sum(VALUE)) 
grass<-add_column(grass, COLS="GRASS", .after=1)
heads<-capriout %>% 
  select(-EMPTY) %>% 
  filter(grepl("HEIF|HEIL|BULL|BULF" ,COLS)) %>%
  filter(ROWS == "LEVL") %>%
  filter(nchar(RALL)==8) %>%
  dplyr::arrange(RALL, Y) %>%
  group_by(RALL,ROWS,Y) %>%
  summarise(amount_1000heads = sum(VALUE)) 
heads<-add_column(heads, COLS="COWS", .after=1)
```

## GENERATE DEMAND FILES FOR LUISABEES,PARSE DATA BY COUNTRY  
```{r}
temp<-bind_cols(arable, perm, grass)

demandall<-select(temp, -one_of("COLS...2", "ROWS...3","RALL...6", "COLS...7", "ROWS...8", "Y...9", "COLS...12", "RALL...11", "ROWS...13", "Y...14"))
demandall <- rename(demandall, Region=RALL...1, Year=Y...4, OtherArableMax=VALUE...5, PermCropMax=VALUE...10, PastureMax=amount_1000ha)
test2 <- mutate(demandall, OtherArableMax=as.integer(OtherArableMax*1000.),PermCropMax=as.integer(PermCropMax*1000.),PastureMax=as.integer(PastureMax*1000.))
demandall <-  mutate_all(demandall, funs(replace(., is.na(.), 0)))
 
```

## Temporal interpolation
```{r}

cols <- c("Year", "OtherArableMax","PermCropMax","PastureMax")
temptointerpolate<-setDT(demandall)[, .SD[match(2010:2070, Year)], by = Region] 
temptointerpolate[, (cols) := lapply(.SD, na.approx, na.rm = FALSE), .SDcols = cols] # actual interpolation (na.approx), rule=2 to always interpolate
interpolated<-temptointerpolate%>%  
  mutate(OtherArable=as.integer(OtherArableMax), PermCrop=as.integer(PermCropMax),Pasture=as.integer(PastureMax)) %>%
  select(-OtherArableMax) %>%
  select(-PermCropMax) %>%
  select(-PastureMax)
interpolated$Region<-substr(interpolated$Region,0,4)

```
## write to files 
```{r}



dir.create(fldr_nominmax)


interpolated %>% 
  mutate(countryiso2 = substr(Region, 1,2)) %>% 
  group_by(countryiso2) %>% 
  nest() %>% 
  walk2(
    .x = .$countryiso2,
    .y = .$data,
    .f = ~ write_csv(.y, file.path(fldr_nominmax, str_c(.x, ".csv")))
   #.f = ~ write_csv(.y, file.path(enddatanew, str_c(.x, ".csv")))
  )


```

<!-- ## expand to annual and min values -->
<!-- ```{r} -->
<!-- cols <- c("Year", "OtherArableMax","PermCropMax","PastureMax") -->
<!-- temptointerpolate<-setDT(demandall)[, .SD[match(2010:2070, Year)], by = Region]  -->
<!-- temptointerpolate[, (cols) := lapply(.SD, na.approx, na.rm = FALSE), .SDcols = cols] -->
<!-- interpolated<-temptointerpolate%>%   -->
<!--   add_column(OtherArableMin = 0, .before = "OtherArableMax")%>% -->
<!--   add_column(PermCropMin = 0, .before = "PermCropMax")%>% -->
<!--   add_column(PastureMin = 0, .before = "PastureMax")%>% -->
<!--   mutate(OtherArableMin=as.integer(OtherArableMax*0.7), PermCropMin=as.integer(PermCropMax*0.7),PastureMin=as.integer(PastureMax*0.7)) %>% -->
<!--   mutate(OtherArableMax=as.integer(OtherArableMax), PermCropMax=as.integer(PermCropMax),PastureMax=as.integer(PastureMax)) -->
<!-- interpolated$Region<-substr(interpolated$Region,0,4) -->

<!-- ``` -->
<!-- #countries<-unique(substr(arable$RALL,1,2)) -->
<!-- ## write to files  -->
<!-- ```{r} -->

<!-- enddata <- "C:\\LUISETTA\\Rproject\\capri4luisabees\\enddata_july2019" -->
<!-- #enddatanew <- "E:/dev/CAPRI/capri4luisabees/enddatanew/" -->

<!-- interpolated  -->

<!-- interpolated %>%  -->
<!--   mutate(countryiso2 = substr(Region, 1,2)) %>%  -->
<!--   group_by(countryiso2) %>%  -->
<!--   nest() %>%  -->
<!--   walk2( -->
<!--     .x = .$countryiso2, -->
<!--     .y = .$data, -->
<!--    .f = ~ write_csv(.y, file.path(enddata, str_c(.x, "_new.csv"))) -->
<!--    #.f = ~ write_csv(.y, file.path(enddatanew, str_c(.x, ".csv"))) -->
<!--   ) -->
<!-- ``` -->

